# Generated by Django 5.0 on 2024-05-21 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='additionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(null=True)),
                ('annual_income', models.IntegerField(null=True)),
                ('uv_name', models.CharField(max_length=150, null=True)),
                ('linkedin', models.URLField(null=True)),
                ('facebook', models.URLField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='basicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(null=True, upload_to='profile_picture/')),
                ('phone_number', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('location', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Barishal', 'Barishal'), ('Rangpur', 'Rangpur'), ('Kumilla', 'Kumilla'), ('Sylhet', 'Sylhet'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi')], max_length=50, null=True)),
                ('education_level', models.CharField(choices=[('SSC', 'SSC'), ('HSC', 'HSC'), ('HONOURS', 'HONOURS'), ('MASTERS', 'MASTERS')], max_length=50, null=True)),
                ('current_job', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Moderator', 'Moderator')], max_length=10, null=True)),
                ('additionalInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.additionalinfo')),
                ('basicInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.basicinfo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
