# Generated by Django 5.0 on 2024-05-22 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='addModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('Used', 'Used'), ('New', 'New')], max_length=15)),
                ('authenticity', models.CharField(choices=[('Original', 'Original'), ('Refurbished', 'Refurbished')], max_length=15)),
                ('brand_name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('negotiable', models.BooleanField()),
                ('picture', models.URLField(null=True)),
                ('contact', models.CharField(max_length=15)),
                ('location', models.CharField(blank=True, choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Barishal', 'Barishal'), ('Rangpur', 'Rangpur'), ('Kumilla', 'Kumilla'), ('Sylhet', 'Sylhet'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi')], max_length=50, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
